### ISSUE TITLE
Infinite loop in `hello.rs`

### ISSUE THREAD

**Issue by blinxen** [cberner/fuser#267]
I am unsure why this happens exactly but if you remove `.skip(offset as usize)` in

https://github.com/cberner/fuser/blob/424bbcaa30a586a6dc99b5019f5e9b9f7755a31f/examples/hello.rs#L106
 
then you will get into a infinite loop. It keeps calling `readdir` over and over and over....

I bet it has something to do with `offset as usize` but my rust-fu is not advanced enough to understand what exactly changes under the hood after the cast. (`gdb` shows that the memory value stays the same :thinking:)

**Comment by dannycjones** [comment]
`readdir` (https://docs.rs/fuser/latest/fuser/trait.Filesystem.html#method.readdir) is an API that the Kernel will want to read multiple pages from. It works by filling up the `reply` until there's no longer any space or no more entries, returning the reply and offset. Then the Kernel will come back to the filesystem with the next offset. When there are no longer any directories to return, an empty buffer should be sent.

When you remove the `skip(offset)` call, the iterator will always have entries and replies will always be sent, telling the Kernel to come back again and again.

You need to keep the skip, or otherwise ensure that when you have returned all the results, the final `readdir` request should reply with no entries.

**Comment by blinxen** [comment]
Thank you for the detailed explanation and fast reply!! I am still playing around with `fuse` and don't really know much yet :D.
